### ISSUE TITLE
[Bug] 'dbt run' hangs when running macro on SFDC objects with many columns 

### ISSUE THREAD

**Issue by Cameron-Skidmore** [fivetran/dbt_salesforce_formula_utils#47] opened 2022-03-17 20:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When doing a 'dbt run' using the macro for the SFDC Account or Opportunity object the build/compile hangs and eventually  the process is killed and the following warning message is displayed:

![Pasted Graphic](https://user-images.githubusercontent.com/86634116/158882581-5e61d11a-df96-4dc2-bc81-cd0edaf65ee1.png)

This happens even when specifying only one or two fields in the 'fileds_to_include' parameter of the macro.

The macro works as expected for other objects in the same project (User, Territory_c, Opportunity_field_history). These objects have much fewer total columns and formula columns, which I'm assuming is the reason they are working and the much larger objects are not.

### Relevant error log or model output

```shell
(see screencap above)

Model does not compile, so there is nothing in the Targets folder of the project.
```

### Expected behavior

A successful build/compile when executing 'dbt run' on models using the macro and referencing the SFDC Account or Opportunity objects, allowing my team to reference the output of the macro in the base models of our current dbt project.

### dbt Project configurations

![Pasted Graphic 1](https://user-images.githubusercontent.com/86634116/158886207-a137aa38-1933-460c-8d01-a93ef7145c0f.png)

### Package versions

![packages yml](https://user-images.githubusercontent.com/86634116/158886484-12660ab1-c563-4d2b-8f54-e75464422670.png)

### What database are you using dbt with?

bigquery

### dbt Version

![installed version 1 0 3](https://user-images.githubusercontent.com/86634116/158886505-41dcae84-a8f7-4c03-aada-eb8852558328.png)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment] 2022-03-17 20:55
Hi @Cameron-Skidmore thanks so much for opening this issue!

Based on your write-up in the issue and from our discussion during the office hour call, I would like to try and modify the package to determine the root cause of the issue. I believe this has to do with memory allocation within dbt before compilation even begins. Therefore, I am going to create a branch of this package that limits (or removes) the number of rows from the base table before the formula macro compilation takes place.

I will post back here with an update for a branch that you will be able to try out. As mentioned, I think a realistic timeline for that patched version of the package will be early next week.

**Comment by fivetran-joemarkiewicz** [comment] 2022-03-22 15:37
Hi @Cameron-Skidmore 👋 

As I mentioned, I was able to get a working branch in place that allows you to specifically include **only** relevant base fields you want in your materialized model that is created from this macro. This new argument `base_fields_to_include` allows you to pass through the select fields you want as a list and only those will be materialized. I hope this will help with the performance issue you have been encountering.

To leverage this working branch you may add the following snippet to your `packages.yml`:
```yml
packages:
    - git: https://github.com/fivetran/dbt_salesforce_formula_utils.git
      revision: feature/only-formulas
      warn-unpinned: false
```

Once you have this in your packages.yml, you may execute `dbt deps` to fetch the changes in this branch. You can now add the new argument and add the fields you want to bring through. Below is an example:
```sql
{{ salesforce_formula_utils.sfdc_formula_view('test_payment_issue_c'
    ,fields_to_include=['is_closed_flag']
    ,base_fields_to_include=['id','name']
) }}
```

Let me know if you have any questions when testing this out, and I hope this helps with performance! 🤞

**Comment by Cameron-Skidmore** [comment] 2022-03-22 18:16
Awesome. Thanks, Joe! I'll test this out today and let you know how it works.

**Comment by Cameron-Skidmore** [comment] 2022-03-22 23:19
Ok, I tested the updated macro with several different field combinations on both the Account and Opportunity object, and unfortunately the problem persists. (two examples below)

![image](https://user-images.githubusercontent.com/86634116/159587802-dc7ece9d-5ad8-4cd6-8ddc-31cbb22b5dbc.png)
![image](https://user-images.githubusercontent.com/86634116/159588368-47c0c5ca-813a-447e-85c8-5d89d0b1e708.png)

**Comment by fivetran-joemarkiewicz** [comment] 2022-03-23 15:03
Thanks for trying this branch out, but I am sorry to see the issue has not been resolved. 

Just to check, did you by chance run a `dbt clean` and then a `dbt deps` after updating the packages.yml?

**Comment by Cameron-Skidmore** [comment] 2022-03-24 01:43
I had not run dbt clean when testing last time. I thought maybe that was the issue. 

But I ran a clean and deps this time, but still no luck. The problem persists :/

**Comment by fivetran-joemarkiewicz** [comment] 2022-03-24 13:55
That's very strange indeed 🤔 

Could you share the contents of the `formula_fields_account.sql` file? I am curious what fields you are calling out in the macro.

**Comment by fivetran-sheringuyen** [comment] 2022-03-25 17:58
Hey @Cameron-Skidmore! I spent some time looking into this and it looks like it's likely a Python/DBT issue which would be outside of our wheelhouse. There seems to have been a similar issue for quite a few customers a while back [here](https://discourse.getdbt.com/t/common-abort-trap-6-leaked-semaphores-error-reported-in-community/810) and there were a couple of recommendations that you may want to try in the dbt slack thread. I would also recommend filing an [issue](https://github.com/dbt-labs/dbt-core/issues) with dbt-core, as I suspect they may be better equipped to help out with this particular issue.

**Comment by Cameron-Skidmore** [comment] 2022-03-29 23:24
@fivetran-joemarkiewicz I was OOO for a while. Getting caught up. Sounds like this issue might not be able to be fixed here based on @fivetran-sheringuyen comments.

For what it is worth, here is the contents of the formula_fields_account.sql file. It is just the macro. 
![image](https://user-images.githubusercontent.com/86634116/160722358-8b87c138-5671-4f11-8e10-7db9824d4252.png)

**Comment by fivetran-joemarkiewicz** [comment] 2022-08-10 14:50
Closing this issue as stated above it is probably best suited to be addressed within dbt-core. Please feel free to re-open the issue if needed.

**Closed by fivetran-joemarkiewicz** 2022-08-10 14:50 UTC
Labels: bug, wontfix
